### ISSUE TITLE
Comments prefixed with 'Изменения'

### ISSUE THREAD

**Issue by dekhaus** [legion-an/django-models-logging#10]
Hi

I noticed that all the Comments created by this plugin are prefixed with the text 'Изменения'.   

Why is that ?

Can this be turned off ?

Thanks
Dave

**Comment by legion-an** [comment]
Hi, this if "changes" in russian :)
, I'll remove this soon
thank you

пт, 27 сент. 2019 г., 14:13 Dave Ekhaus <notifications@github.com>:
