### ISSUE TITLE
 Update to django.urls.re_path() because django.conf.urls.url() is deprecated

### ISSUE THREAD

**Issue by FernandoCelmer** [legion-an/django-models-logging#21]
**Python3.9 / Django==4.0** -- https://docs.djangoproject.com/en/4.0/ref/urls/

`File "/home/........./venv/lib/python3.9/site-packages/models_logging/admin.py", line 129, in get_urls
    urls.insert(0, url(r'^(.+)/revert/$', wrap(self.revert_view), name='revert_changes'),)`
`File "/home/........./lib/python3.9/site-packages/django/conf/urls/__init__.py", line 16, in url
    warnings.warn(
django.utils.deprecation.RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().`

**Comment by FernandoCelmer** [comment]
#21 - Update to django.urls.re_path() because django.conf.urls.url() is deprecated #22

**Comment by creyD** [comment]
This is closed with #27 as well
