### ISSUE TITLE
Migration 008 is missing in the repository

### ISSUE THREAD

**Issue by alevgenk** [legion-an/django-models-logging#31]
Hi!
I found that one migration is missing in the current codebase.
Last migration in the repo is [0007_migrate_old_fields.py](https://github.com/legion-an/django-models-logging/blob/master/models_logging/migrations/0007_migrate_old_fields.py)
But after running `makemigrations` I can see new `008` migration was created:

```
# Generated by Django 3.2.11 on 2022-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_logging', '0007_migrate_old_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]

```

**Comment by creyD** [comment]
Thanks for the tip! Will add the migration as soon as possible.

**Comment by creyD** [comment]
I couldn't reproduce it. Maybe this is because you had the module installed before the 2.0 upgrade?

**Comment by alevgenk** [comment]
Just tried with an empty project, but this issue still occurs.
Here are steps to reproduce:

1. Create empty project and venv with such reqirements.txt
```
Django==3.2.11
django-models-logging==2.0.0
```
2. pip install
3. django-admin startproject testsite
4. python ./testsite/manage.py migrate
5. python ./testsite/manage.py makemigrations

Result is 
```
Migrations for 'models_logging':
  venv/lib/python3.7/site-packages/models_logging/migrations/0008_auto_20220407_1428.py
    - Alter field id on change
    - Alter field id on revision
```

So, after step 5 I can see new migration 008 in the package migrations dir.

After all, I found the [reason](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) of such behavior.
So, one of the solutions is to add string
```default_auto_field = 'django.db.models.AutoField'```
to [LoggingConfig](https://github.com/legion-an/django-models-logging/blob/127a29ee5fdebea883c7d65bc2bad644a0b5459c/models_logging/apps.py#L8) 
After that, migration will not be created.

**Comment by creyD** [comment]
So I added it to the app and the testapp (https://github.com/legion-an/django-models-logging/commit/e85f57be92c8fa2c37808379772ab1a9bea0a674). It didn't happen before for me because I was using Django 4.0 I guess.
