### ISSUE TITLE
BUG with circular import

### ISSUE THREAD

**Issue by creyD** [legion-an/django-models-logging#35]
Just upgraded my instance and tried to migrate the changes and it stated a circular import here. Can you confirm, that this is not only on my side? @legion-an 

![Screenshot 2022-12-09 at 10 51 22](https://user-images.githubusercontent.com/15138480/206674551-33051bd2-5c15-48ac-8680-5a21060782b0.png)

**Comment by fazardini** [comment]
I want to use your package but I can't because I see this  Error too.
Can you fix it? 
Can I help you to fix it?
Thanks

> Just upgraded my instance and tried to migrate the changes and it stated a circular import here. Can you confirm, that this is not only on my side? @legion-an
> 
> ![Screenshot 2022-12-09 at 10 51 22](https://user-images.githubusercontent.com/15138480/206674551-33051bd2-5c15-48ac-8680-5a21060782b0.png)

**Comment by legion-an** [comment]
I will check this

**Comment by fazardini** [comment]
> I will check this

in settings.py file line 34 I think you should convet 'models_logging.utils.get_change_extras' to 'models_logging.helpers.get_change_extras'. because utils file has not get_change_extras function.

**Comment by legion-an** [comment]
I fixed this bug and uploaded a new version to pypi (2.1.1)

I'm sorry, I didn't encounter this problem because I have my custom `JSON_ENCODER` and `GET_CHANGE_EXTRAS_PATH`

**Comment by fazardini** [comment]
> I fixed this bug and uploaded a new version to pypi (2.1.1)
> 
> I'm sorry, I didn't encounter this problem because I have my custom `JSON_ENCODER` and `GET_CHANGE_EXTRAS_PATH`
> 
> Please confirm that it works for you

Thank you so much. This problem has been resolved. 
How can I write all log in one file?
Can I write Logs in file without saving in database ???

**Comment by fazardini** [comment]
> I fixed this bug and uploaded a new version to pypi (2.1.1)
> 
> I'm sorry, I didn't encounter this problem because I have my custom `JSON_ENCODER` and `GET_CHANGE_EXTRAS_PATH`
> 
> Please confirm that it works for you

![Screenshot from 2022-12-17 15-51-13](https://user-images.githubusercontent.com/24295429/208241874-daebbda1-34cd-4033-88ce-42d66d0f6c6f.png)

I saw this error in admin page of logs. (admin/models_logging/change/)

**Comment by creyD** [comment]
@fazardini Did you apply the migrations with `python manage.py migrate`? @legion-an Thanks!

**Comment by fazardini** [comment]
> @fazardini Did you apply the migrations with `python manage.py migrate`? @legion-an Thanks!

My problem is solved. It was about my database. Thank you
Can I write Logs in file without saving in database ???

**Comment by legion-an** [comment]
No, there is no possibility to write changes to database. Theoretically you can put JSON to logs, but it's definitely not the goal of this package :)

**Comment by fazardini** [comment]
Thank you.
How can I see all Logs in a json file?
Is it possible with this package?

**Comment by legion-an** [comment]
no, it does not write any logs into a json

when I put my last comment, I meant you can try to override the behavior, so that it will write data to logs.

**Comment by creyD** [comment]
@legion-an I can confirm that this is now gone in the latest 2.3 version!

**Comment by legion-an** [comment]
@creyD I thought it has been fixed a long time ago actually :)
